server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 13851176590++

mybatis:
  sysFileMapper-locations:
    - classpath:sysFileMapper/*.xml
    - classpath*:com/**/sysFileMapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springfox:
  documentation:
    enabled: true

