server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 13851176590++
  redis:
    host: 1.117.34.49 # Redis服务器地址
    database: 3 # Redis数据库索引（默认为0）
    port: 6378 # Redis服务器连接端口
#    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
#    cluster:
#      nodes:
#        - 192.168.6.139:6391
#        - 192.168.6.139:6392
#        - 192.168.6.139:6393
#        - 192.168.6.139:6394
#        - 192.168.6.139:6395
#        - 192.168.6.139:6396
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springfox:
  documentation:
    enabled: true
